"""Add user global goals

Revision ID: 74da101adbc0
Revises: ec0334756c58
Create Date: 2026-05-29 20:54:25.189912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74da101adbc0'
down_revision: Union[str, Sequence[str], None] = 'ec0334756c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_global_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('daily_time_target', sa.Integer(), nullable=True),
    sa.Column('daily_card_target', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_global_goals_id'), 'user_global_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_global_goals_user_id'), 'user_global_goals', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_global_goals_user_id'), table_name='user_global_goals')
    op.drop_index(op.f('ix_user_global_goals_id'), table_name='user_global_goals')
    op.drop_table('user_global_goals')
    # ### end Alembic commands ###
