"""Add UserTelegramConfig table

Revision ID: e56478733583
Revises: 74da101adbc0
Create Date: 2026-05-30 20:45:34.767139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56478733583'
down_revision: Union[str, Sequence[str], None] = '74da101adbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_telegram_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('connect_token', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reminder_time', sa.String(length=10), nullable=True),
    sa.Column('streak_guard_enabled', sa.Boolean(), nullable=True),
    sa.Column('weekly_summary_enabled', sa.Boolean(), nullable=True),
    sa.Column('inactivity_alert_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_telegram_configs_connect_token'), 'user_telegram_configs', ['connect_token'], unique=True)
    op.create_index(op.f('ix_user_telegram_configs_user_id'), 'user_telegram_configs', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_configs_user_id'), table_name='user_telegram_configs')
    op.drop_index(op.f('ix_user_telegram_configs_connect_token'), table_name='user_telegram_configs')
    op.drop_table('user_telegram_configs')
    # ### end Alembic commands ###
